#!/usr/bin/php -q
<?php
require 'phpagi-2.20/phpagi.php';
$agi = new AGI();

$number = preg_replace("#[^0-9]#","",$agi->request["agi_callerid"]);
$name = "";

$db = 'asteriskcdrdb';
$dbuser = 'asterisk';
$dbpass = 'Ajslk319Yjalk1298Auh';
$dbhost = 'localhost';

mysql_connect($dbhost,$dbuser,$dbpass);
mysql_select_db("$db");
mysql_set_charset("utf8");

mysql_query("UPDATE cdr SET FromNumber='$number' WHERE uniqueid='".$agi->request["agi_uniqueid"]."'");

$row = mysql_query("SELECT Name FROM phonebook WHERE Number LIKE '%$number%'");
if (mysql_num_rows($row) == 1) {
        $row=mysql_fetch_array($row);
        if ($row["Name"]) $name = $row["Name"];
}
$agi->set_variable("MySQLName", $name);
?>
